version: "3.9"

services:
  indexer:
    build: ./backend
    volumes:
      - ./incoming:/data      # <-- tout ton incoming devient directement /data
      - db:/db
    ports:
      - "8000:8000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install axios && npm run dev -- --host 0.0.0.0 --port 3000"
volumes:
  extracted:
  db: