services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./incoming:/data
      - db:/db
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - "9000:9000"
    environment:
      - SECRET_KEY=supersecretkey

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "9001:9001"
    command: >
      sh -c "
        if [ ! -d node_modules ]; then
          echo 'Installation des dépendances...'
          npm install
        fi &&
        echo 'Démarrage du frontend...' &&
        npm run dev -- --host 0.0.0.0 --port 9001
      "

volumes:
  db:
